# Generated by Django 3.0.7 on 2020-08-10 15:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('summary', models.TextField(verbose_name='short summary')),
                ('description', models.TextField(blank=True)),
                ('type', models.IntegerField(choices=[(1, 'Website'), (2, 'API'), (3, 'Mobile application'), (4, 'Web scraping'), (5, 'Library')])),
                ('private', models.BooleanField(default=False)),
                ('date', models.DateField()),
                ('featured', models.BooleanField(default=False)),
                ('url', models.URLField(blank=True)),
                ('respository', models.URLField(blank=True)),
                ('thumbnail', models.ImageField(upload_to='')),
                ('video', models.URLField(blank=True)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('technologies', models.ManyToManyField(to='portfolio.Technology')),
            ],
            options={
                'verbose_name': 'Past Project',
                'verbose_name_plural': 'Past Projects',
                'ordering': ('-featured', '-date'),
            },
        ),
    ]
