# Generated by Django 3.0.7 on 2020-08-10 16:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20200810_1853'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, verbose_name='client name')),
                ('photo', models.ImageField(upload_to='')),
                ('testimony', models.TextField()),
                ('featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False, verbose_name='published')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-featured', '-created_at'),
            },
        ),
        migrations.AlterField(
            model_name='project',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='published'),
        ),
        migrations.CreateModel(
            name='ProjectPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120)),
                ('photo', models.ImageField(upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='portfolio.Project')),
            ],
            options={
                'verbose_name': 'Project Photo',
                'verbose_name_plural': 'Project Photos',
                'ordering': ('created_at',),
            },
        ),
    ]
