# Generated by Django 3.0.7 on 2020-08-10 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20200810_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='title',
            field=models.CharField(default='', max_length=120, verbose_name='client title'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='name',
            field=models.CharField(max_length=120, verbose_name='full name'),
        ),
    ]
