# Generated by Django 3.0.7 on 2020-08-12 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_auto_20200812_0459'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='respository',
            new_name='repository',
        ),
    ]
