# Generated by Django 3.0.7 on 2020-08-12 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_auto_20200812_0505'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='thumbnail_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='thumbnail_width',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectphoto',
            name='photo_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectphoto',
            name='photo_width',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(blank=True, height_field='thumbnail_height', help_text='Recommended size is 429x286 px.', null=True, upload_to='', width_field='thumbnail_width'),
        ),
        migrations.AlterField(
            model_name='projectphoto',
            name='photo',
            field=models.ImageField(height_field='photo_height', help_text='Recommended size is 600x400 px.', upload_to='', width_field='photo_width'),
        ),
    ]
