# Generated by Django 3.0.7 on 2020-08-12 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_auto_20200812_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='facebook',
            field=models.URLField(blank=True, null=True, verbose_name='facebook link'),
        ),
        migrations.AddField(
            model_name='project',
            name='linkedIn',
            field=models.URLField(blank=True, null=True, verbose_name='linkedIn link'),
        ),
        migrations.AddField(
            model_name='project',
            name='twitter',
            field=models.URLField(blank=True, null=True, verbose_name='twitter link'),
        ),
    ]
