# Generated by Django 3.0.7 on 2020-08-12 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_auto_20200812_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='facebook',
            field=models.URLField(blank=True, default='', verbose_name='facebook link'),
        ),
        migrations.AlterField(
            model_name='project',
            name='linkedIn',
            field=models.URLField(blank=True, default='', verbose_name='linkedIn link'),
        ),
        migrations.AlterField(
            model_name='project',
            name='twitter',
            field=models.URLField(blank=True, default='', verbose_name='twitter link'),
        ),
    ]
