# Generated by Django 3.0.7 on 2020-08-13 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_auto_20200812_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='height_width',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='photo_width',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='photo',
            field=models.ImageField(blank=True, height_field='photo_height', help_text='Recommended size is 80x80 px.', null=True, upload_to='', width_field='photo_width'),
        ),
    ]
