# Generated by Django 3.0.7 on 2020-08-13 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_auto_20200813_1509'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonial',
            old_name='height_width',
            new_name='photo_height',
        ),
    ]
