# Generated by Django 3.0.7 on 2020-08-13 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_auto_20200813_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(default='', height_field='thumbnail_height', help_text='Recommended size is 429x286 px.', upload_to='', width_field='thumbnail_width'),
            preserve_default=False,
        ),
    ]
