# Generated by Django 3.0.7 on 2020-08-13 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0017_testimonial_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='gender',
        ),
    ]
