# Generated by Django 3.0.7 on 2020-08-13 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0018_remove_testimonial_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technology',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
