# Generated by Django 3.0.7 on 2020-08-08 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_skill_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ('order',)},
        ),
    ]
