# Generated by Django 3.0.7 on 2020-08-08 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_auto_20200808_2304'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ('order', 'title')},
        ),
    ]
