# Generated by Django 3.0.7 on 2020-08-08 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_education_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='experience',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
