# Generated by Django 3.0.7 on 2020-08-08 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_auto_20200808_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='experience',
            name='end',
            field=models.IntegerField(blank=True, null=True, verbose_name='end date'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='start',
            field=models.IntegerField(verbose_name='start year'),
        ),
    ]
