# Generated by Django 3.0.7 on 2020-08-08 23:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0008_experience_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120)),
                ('institute', models.CharField(help_text='Training institution. Example: College, University, etc', max_length=120)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('date', models.DateField()),
                ('link', models.URLField()),
                ('is_published', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Awarded Certificates',
                'ordering': ('date',),
            },
        ),
        migrations.AlterField(
            model_name='education',
            name='institute',
            field=models.CharField(help_text='Educational institution. Example: College, University, etc', max_length=120),
        ),
    ]
