# Generated by Django 3.0.7 on 2020-08-09 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0009_auto_20200809_0233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificate',
            old_name='logo',
            new_name='icon',
        ),
    ]
