# Generated by Django 3.0.7 on 2020-08-13 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0010_auto_20200809_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='icon_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='icon_width',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='icon',
            field=models.ImageField(blank=True, height_field='icon_height', help_text='Recommended size is 70x21 px.', null=True, upload_to='', width_field='icon_width'),
        ),
    ]
